# version: '3.8'

services:
  mcp-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - PG_CONN_STR=postgresql://testuser:testpass@postgres:5432/testdb
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn mcp_api_server:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
